### ISSUE TITLE
Decrypting firmware

### ISSUE THREAD

**Issue by H4niz** [EPhaha/IOT_vuln#2]
**嗨，EPhaha，**
我看到了你的回购并试图跟进你的发现。 但是，我无法解密/模拟器固件（rsf，fat），你能帮我解密吗？ 谢谢！

**Comment by EPhaha** [comment]
please give me your email , Thanks~

**Comment by H4niz** [comment]
Gmail: haniz.cons@gmail.com
Thanks!

**Comment by 1481378837** [comment]
你好，EPhaha。我对你的研究很感兴趣，并尝试复现你的实验，但是固件不能通过fat进行仿真，希望得到你修改后的固件，谢谢~
